### ISSUE TITLE
Face detection

### ISSUE THREAD

**Issue by DrPerryCoke** [TheTimeWalker/wallpanel-android#8]
- Device: Samsung Note 10.1 (SM-8000)
 - OS: Android 9
 
Hi! I understand Google services are mandatory? I just flashed the N-8000 tablet on android 9, and decided not to install services. But now face detection doesn't work. When exiting the settings , this is what he writes:
Missing appropriate libraries to process Face detection or Barcode reading. These features may not work on this device.

**Comment by TheTimeWalker** [comment]
Unfortunately, the face and barcode detection requires Google Services as it leverages the Mobile Vision API to do this.

**Comment by GinjNinj** [comment]
Also having this issue, but having updated Google Account Manager, Google Services Framework, Google Play Services and  play store the issue is still there. Any advice on how to get it working on a Fire HD 8 tablet?

**Comment by BillyFKidney** [comment]
**Describe the bug**
Facial recognition and barcode reading fail.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'Settings'
2. Scroll down to and press 'Camera Settings'
3. Enable the toggle for 'Camera Enabled'
4. Scroll down to and press 'Camera Test'
5. Ensure that Wall Panel has access to the camera
6. Press back
7. Press 'Face Detection'
8. Enable the toggle for 'Face Detection Enabled'
9. Press back until you reach the dashboard

2. 
**Expected behavior**
Facial Detection to be available

**Screenshots**
Wall Panel Dashboard
![IMG_3566](https://user-images.githubusercontent.com/65253277/183308776-622bf57e-112c-4900-98a2-23572a5d4482.jpg)


**Smartphone (please complete the following information):**
 Device 1
 - Device: Fire HD 8 Plus (10th Generation)
 - OS: Fire OS 7.3.2.3
 
 Device 2
 - Device: Fire HD 10 (11th Generation)
 - OS: Fire OS 7.3.2.3


**Additional context**
Wall Panel Version: 0.10.0 Build 1

Google Play Store and supporting services are installed via Fire Toolbox v28.9
